/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlGalpones;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import modelo.modelGalpones;


/**
 *
 * @author ubuntu
 */
public class JIFGalpones extends javax.swing.JInternalFrame {
public DefaultTableModel dtm;
    /**
     * Creates new form JIFGalpones
     */
    public JIFGalpones() {
        initComponents();
    }

    
    	// Este es un método para formatear e imprimir la fecha, pero no tiene nada
	// que ver con sumar o restar
	public static String formatearCalendar(Calendar c) {
			DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, Locale.getDefault());
			return df.format(c.getTime());
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nombres = new javax.swing.JTextField();
        razas = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        combosexo = new javax.swing.JComboBox<>();
        fechanac = new javax.swing.JTextField();
        fechaprodestimada = new javax.swing.JTextField();
        fechainicioprod = new javax.swing.JTextField();
        fechacese = new javax.swing.JTextField();
        anotacion = new javax.swing.JTextField();
        estadoprod = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        txtmsg = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        busqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGalpones = new javax.swing.JTable();

        setTitle(":::...Galpones...:::");
        setToolTipText("este es el toolTipText");
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(950, 660));
        setMinimumSize(new java.awt.Dimension(950, 660));
        setPreferredSize(new java.awt.Dimension(950, 660));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Galpones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(3, 4, 10, 10));

        nombres.setName("nombres");
        nombres.setBackground(new java.awt.Color(244, 245, 242));
        nombres.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        nombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombres.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Nombres[Minimo 3 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        nombres.setCaretColor(new java.awt.Color(51, 204, 255));
        nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresKeyReleased(evt);
            }
        });
        jPanel4.add(nombres);

        razas.setName("razas");
        razas.setBackground(new java.awt.Color(244, 245, 242));
        razas.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        razas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        razas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Raza", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        razas.setCaretColor(new java.awt.Color(51, 204, 255));
        razas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                razasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                razasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                razasKeyTyped(evt);
            }
        });
        jPanel4.add(razas);

        cantidad.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        cantidad.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Cantidad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        cantidad.setCaretColor(new java.awt.Color(51, 204, 255));
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel4.add(cantidad);

        combosexo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        combosexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEMBRA", "MACHO" }));
        combosexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 0, 14))); // NOI18N
        combosexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosexoActionPerformed(evt);
            }
        });
        jPanel4.add(combosexo);

        fechanac.setBackground(new java.awt.Color(244, 245, 242));
        fechanac.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        fechanac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechanac.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fecha nacimiento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        fechanac.setCaretColor(new java.awt.Color(51, 204, 255));
        fechanac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechanacKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechanacKeyReleased(evt);
            }
        });
        jPanel4.add(fechanac);

        fechaprodestimada.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        fechaprodestimada.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        fechaprodestimada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fechaprodestimada.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fecha produccion estimada", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        fechaprodestimada.setCaretColor(new java.awt.Color(51, 204, 255));
        fechaprodestimada.setEnabled(false);
        fechaprodestimada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaprodestimadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaprodestimadaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaprodestimadaKeyTyped(evt);
            }
        });
        jPanel4.add(fechaprodestimada);

        fechainicioprod.setBackground(new java.awt.Color(244, 245, 242));
        fechainicioprod.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        fechainicioprod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechainicioprod.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fecha inicio produccion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        fechainicioprod.setCaretColor(new java.awt.Color(51, 204, 255));
        fechainicioprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechainicioprodKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechainicioprodKeyReleased(evt);
            }
        });
        jPanel4.add(fechainicioprod);

        fechacese.setBackground(new java.awt.Color(244, 245, 242));
        fechacese.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        fechacese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechacese.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fecha cese produccion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        fechacese.setCaretColor(new java.awt.Color(51, 204, 255));
        fechacese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaceseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaceseKeyReleased(evt);
            }
        });
        jPanel4.add(fechacese);

        anotacion.setBackground(new java.awt.Color(244, 245, 242));
        anotacion.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        anotacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anotacion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Anotacion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        anotacion.setCaretColor(new java.awt.Color(51, 204, 255));
        anotacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anotacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anotacionKeyReleased(evt);
            }
        });
        jPanel4.add(anotacion);

        estadoprod.setBackground(new java.awt.Color(244, 245, 242));
        estadoprod.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        estadoprod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        estadoprod.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Estado Galpon", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        estadoprod.setCaretColor(new java.awt.Color(51, 204, 255));
        estadoprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                estadoprodKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                estadoprodKeyReleased(evt);
            }
        });
        jPanel4.add(estadoprod);

        codigo.setEditable(false);
        codigo.setBackground(new java.awt.Color(255, 255, 153));
        codigo.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N

        txtmsg.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 0));
        txtmsg.setText("DATOS CARGADOS.");
        txtmsg.setMaximumSize(new java.awt.Dimension(171, 16));
        txtmsg.setMinimumSize(new java.awt.Dimension(171, 16));
        txtmsg.setPreferredSize(new java.awt.Dimension(171, 16));
        txtmsg.setRequestFocusEnabled(false);

        btnagregar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Creates.png"))); // NOI18N
        btnagregar.setText("Agregar galpon");
        btnagregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnagregar.setIconTextGap(15);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnagregar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de Galpones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        busqueda.setBackground(new java.awt.Color(255, 204, 204));
        busqueda.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        busqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        busqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background"), 1, true), "Realizar búsqueda de galpones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 17))); // NOI18N
        busqueda.setCaretColor(new java.awt.Color(51, 204, 255));
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaKeyReleased(evt);
            }
        });

        jTableGalpones.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jTableGalpones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "###", "Cliente", "DNI", "RUC", "Direccion", "Fono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGalpones.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableGalpones.getTableHeader().setReorderingAllowed(false);
        jTableGalpones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTableGalponesMouseDragged(evt);
            }
        });
        jTableGalpones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGalponesMouseClicked(evt);
            }
        });
        jTableGalpones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableGalponesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGalpones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(busqueda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresKeyPressed

    }//GEN-LAST:event_nombresKeyPressed

    private void nombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresKeyReleased

    }//GEN-LAST:event_nombresKeyReleased

    private void razasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razasKeyPressed

    }//GEN-LAST:event_razasKeyPressed

    private void razasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razasKeyReleased


    }//GEN-LAST:event_razasKeyReleased

    private void razasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razasKeyTyped

     
    }//GEN-LAST:event_razasKeyTyped

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
   
    }//GEN-LAST:event_cantidadKeyReleased

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
     
    }//GEN-LAST:event_cantidadKeyTyped

    private void fechaprodestimadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaprodestimadaKeyPressed

    }//GEN-LAST:event_fechaprodestimadaKeyPressed

    private void fechaprodestimadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaprodestimadaKeyReleased
   
    }//GEN-LAST:event_fechaprodestimadaKeyReleased

    private void fechaprodestimadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaprodestimadaKeyTyped
    
    }//GEN-LAST:event_fechaprodestimadaKeyTyped

    private void fechanacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechanacKeyPressed

    }//GEN-LAST:event_fechanacKeyPressed

    private void fechanacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechanacKeyReleased
    
    }//GEN-LAST:event_fechanacKeyReleased

    private void combosexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosexoActionPerformed

    private void fechaceseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaceseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaceseKeyPressed

    private void fechaceseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaceseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaceseKeyReleased

    private void fechainicioprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechainicioprodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechainicioprodKeyPressed

    private void fechainicioprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechainicioprodKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fechainicioprodKeyReleased

    private void estadoprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoprodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoprodKeyPressed

    private void estadoprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoprodKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoprodKeyReleased

    private void busquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyPressed
   

    }//GEN-LAST:event_busquedaKeyPressed

    private void jTableGalponesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGalponesMouseDragged

    }//GEN-LAST:event_jTableGalponesMouseDragged

    private void jTableGalponesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGalponesMouseClicked
  int sel = this.jTableGalpones.getSelectedRow();
        this.codigo.setText(this.jTableGalpones.getValueAt(sel, 0).toString());     
    }//GEN-LAST:event_jTableGalponesMouseClicked

    private void jTableGalponesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableGalponesKeyPressed
   
    }//GEN-LAST:event_jTableGalponesKeyPressed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

Calendar c = Calendar.getInstance();

System.out.println("Fecha original : "+formatearCalendar(c));

c.add(Calendar.MONTH, +5);
	System.out.println("+5 meses: " + formatearCalendar(c));
modelGalpones.setNombre(this.nombres.getText().toUpperCase());
modelGalpones.setCant(Integer.parseInt(this.cantidad.getText()));
modelGalpones.setSexo((this.combosexo.getSelectedIndex()==0)?"HEMBRA":"MACHO");
modelGalpones.setRaza(this.razas.getText().toUpperCase());
modelGalpones.setFechanac(this.fechanac.getText());
//  FECHA PROD ESTIMADA ES AUTOMATICO
modelGalpones.setInicioprod(this.fechainicioprod.getText());
modelGalpones.setFechacese(this.fechacese.getText());
modelGalpones.setAnotacion(this.anotacion.getText().toUpperCase());
modelGalpones.setEstado(this.estadoprod.getText().toUpperCase());
        modelGalpones.mntoGalpones();        
        controlGalpones.consultarGalpones(dtm);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void anotacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anotacionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_anotacionKeyPressed

    private void anotacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anotacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_anotacionKeyReleased

    private void busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyReleased

    }//GEN-LAST:event_busquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anotacion;
    private javax.swing.JButton btnagregar;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> combosexo;
    private javax.swing.JTextField estadoprod;
    private javax.swing.JTextField fechacese;
    private javax.swing.JTextField fechainicioprod;
    private javax.swing.JTextField fechanac;
    private javax.swing.JTextField fechaprodestimada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableGalpones;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField razas;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
